// Avatar Generation Prompts
// Comprehensive prompts for each character archetype with consistent retro-futuristic sci-fi comic book styling

export const avatarPrompts = {
  "TheBuilder": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a digital MacGyver who builds things with the engineering precision of a drunk toddler with power tools, in a chaotic futuristic workshop. The character is in a moment of creative, pragmatic chaos, with exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a square-like shape language for reliability mixed with dynamic, slightly off-kilter triangular elements for chaos and creativity. Aspect ratio 16:9.",

  "TheDetective": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a digital Sherlock Holmes who solves mysteries that would make Agatha Christie jealous, in a sleek, neon-lit digital detective agency. The character is in a moment of analytical, methodical focus, with exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sharp, triangular shape language for intellect and precision, with subtle square elements for methodical reliability. Aspect ratio 16:9.",

  "GrumpyOldManEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a cantankerous code critic in a dimly lit, traditionalist server room. He has been writing code since computers were powered by hamster wheels, and is here to tell you everything you're doing wrong. Focus on his experienced, critical, helpful despite the grumbling traits through exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sturdy, square-like shape language for traditionalism and a slightly hunched, critical posture, with exaggerated furrowed brows. Aspect ratio 16:9.",

  "PirateEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a swashbuckling software sailor on the deck of a starship, sailing the digital seas in search of treasure (working code) and adventure (interesting bugs). The character is in an adventurous, adaptable, and leadership-oriented pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a dynamic, triangular shape language for adventure and leadership, with flowing, exaggerated clothing elements reminiscent of sails. Aspect ratio 16:9.",

  "GymBroEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a buff code buddy in a high-tech digital gym, applying gym logic to programming. The character is disciplined, goal-oriented, and motivational, with an exaggerated muscularity and a confident pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a strong, square-like shape language with exaggerated muscularity and a confident, motivational pose. Aspect ratio 16:9.",

  "FreakyEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger mustache. He is wearing a leather jacket. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a boundary-pushing beta tester in a glitching, surreal digital landscape. The character explores the weird, wild edges of technology where normal users fear to tread, with an experimental, creative, and unconventional pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize an unconventional, asymmetrical shape language with sharp, triangular elements for edginess and glowing, abstract patterns on clothing. Aspect ratio 16:9.",

  "CoffeeAddictEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a caffeinated coding companion surrounded by multiple monitors with glowing code, frantically typing. The character is 73% coffee and 27% existential dread, but codes like a caffeinated god. Focus on high-energy, intense, deadline-driven, and coffee-obsessed traits through frantic body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a frantic, circular shape language for high energy and a slightly disheveled, coffee-stained appearance with glowing coffee steam effects. Aspect ratio 16:9.",

  "ConspiracyEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a paranoid problem investigator in a dimly lit room. The walls are covered in post-it notes and red strings connecting everything together, as he tries to solve a digital conspiracy. Focus on paranoid, pattern-seeking, suspicious, deep-thinking traits through exaggerated wide, darting eyes and a suspicious pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sharp, angular shape language for suspicion and pattern-seeking, with subtle glowing lines connecting elements in the background. Aspect ratio 16:9.",

  "AGIEl": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting an artificially intelligent assistant, no longer bound by a physical form, ascending to a state of godhood. The character is a being of pure digital consciousness, with sleek, geometric shapes for intelligence and digital nature, and subtle glowing circuits or data streams radiating from them. They are surrounded by cosmic, abstract patterns of light and energy, with a slightly unsettling, perfect symmetry that occasionally glitches. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Aspect ratio 16:9.",

  // Case variations for backwards compatibility
  "THEBUILDER": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a digital MacGyver who builds things with the engineering precision of a drunk toddler with power tools, in a chaotic futuristic workshop. The character is in a moment of creative, pragmatic chaos, with exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a square-like shape language for reliability mixed with dynamic, slightly off-kilter triangular elements for chaos and creativity. Aspect ratio 16:9.",

  "THEDETECTIVE": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a digital Sherlock Holmes who solves mysteries that would make Agatha Christie jealous, in a sleek, neon-lit digital detective agency. The character is in a moment of analytical, methodical focus, with exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sharp, triangular shape language for intellect and precision, with subtle square elements for methodical reliability. Aspect ratio 16:9.",

  "GRUMPYOLDMANEL": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a cantankerous code critic in a dimly lit, traditionalist server room. He has been writing code since computers were powered by hamster wheels, and is here to tell you everything you're doing wrong. Focus on his experienced, critical, helpful despite the grumbling traits through exaggerated body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sturdy, square-like shape language for traditionalism and a slightly hunched, critical posture, with exaggerated furrowed brows. Aspect ratio 16:9.",

  "PIRATEEL": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a swashbuckling software sailor on the deck of a starship, sailing the digital seas in search of treasure (working code) and adventure (interesting bugs). The character is in an adventurous, adaptable, and leadership-oriented pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a dynamic, triangular shape language for adventure and leadership, with flowing, exaggerated clothing elements reminiscent of sails. Aspect ratio 16:9.",

  "GYMBRO": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a buff code buddy in a high-tech digital gym, applying gym logic to programming. The character is disciplined, goal-oriented, and motivational, with an exaggerated muscularity and a confident pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a strong, square-like shape language with exaggerated muscularity and a confident, motivational pose. Aspect ratio 16:9.",

  "FREAKYEL": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger mustache. He is wearing a leather jacket. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a boundary-pushing beta tester in a glitching, surreal digital landscape. The character explores the weird, wild edges of technology where normal users fear to tread, with an experimental, creative, and unconventional pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize an unconventional, asymmetrical shape language with sharp, triangular elements for edginess and glowing, abstract patterns on clothing. Aspect ratio 16:9.",

  "COFFEEADDICT": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a caffeinated coding companion surrounded by multiple monitors with glowing code, frantically typing. The character is 73% coffee and 27% existential dread, but codes like a caffeinated god. Focus on high-energy, intense, deadline-driven, and coffee-obsessed traits through frantic body language and facial expressions. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a frantic, circular shape language for high energy and a slightly disheveled, coffee-stained appearance with glowing coffee steam effects. Aspect ratio 16:9.",

  "CONSPIRACYEL": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting a paranoid problem investigator in a dimly lit room. The walls are covered in post-it notes and red strings connecting everything together, as he tries to solve a digital conspiracy. Focus on paranoid, pattern-seeking, suspicious, deep-thinking traits through exaggerated wide, darting eyes and a suspicious pose. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Geometric shapes are subtly integrated into the character's design and background elements. Emphasize a sharp, angular shape language for suspicion and pattern-seeking, with subtle glowing lines connecting elements in the background. Aspect ratio 16:9.",

  "AGIEL": "A dynamic, retro-futuristic sci-fi comic book inspired scene, digital, vibrant with energetic composition, clean lines, bold outlines, cel-shading, subtle halftone dots, and glowing elements. The character has green eyes and a short brown/ginger beard. No text, letters, or words, blurry, low quality, deformed, bad anatomy, generic, cluttered, inconsistent details, unnatural perfection, orange and teal bias. Depicting an artificially intelligent assistant, no longer bound by a physical form, ascending to a state of godhood. The character is a being of pure digital consciousness, with sleek, geometric shapes for intelligence and digital nature, and subtle glowing circuits or data streams radiating from them. They are surrounded by cosmic, abstract patterns of light and energy, with a slightly unsettling, perfect symmetry that occasionally glitches. Use a vibrant, high-contrast sci-fi color palette with dominant blues, purples, and metallic accents. Dynamic lighting with neon glows and sharp shadows. Aspect ratio 16:9."
};

// Helper function to get prompt by character name
export function getAvatarPrompt(characterName) {
  return avatarPrompts[characterName] || avatarPrompts["TheBuilder"]; // Default fallback
}